import React from 'react';
import Link from 'next/link';
import { FileText, ArrowLeft } from 'lucide-react';

export const metadata = {
  title: 'Terms of Service & Disclaimer | GP 2026 Finance',
  description: 'Terms of Service and financial disclaimer for Ganesh Puja 2026 Portal'
};

export default function TermsPage() {
  return (
    <div className="max-w-3xl mx-auto px-4 py-8 space-y-6 text-slate-200">
      <Link href="/" className="inline-flex items-center space-x-1.5 text-xs text-orange-400 hover:text-orange-300 font-bold mb-2">
        <ArrowLeft className="w-4 h-4" />
        <span>Back to Portal Home</span>
      </Link>

      <div className="bg-slate-900 border border-slate-800 rounded-2xl p-6 shadow-2xl space-y-4">
        <div className="flex items-center space-x-3 border-b border-slate-800 pb-4">
          <FileText className="w-8 h-8 text-amber-400" />
          <div>
            <h1 className="text-xl font-bold text-slate-100">Terms of Service & Legal Disclaimer</h1>
            <p className="text-xs text-slate-400 font-medium">Ganesh Puja 2026 Financial Management Portal (gp2026.luhurachati.com)</p>
          </div>
        </div>

        <div className="space-y-4 text-xs text-slate-300 leading-relaxed">
          <section className="space-y-1">
            <h2 className="text-sm font-bold text-amber-400">1. Purpose of the Application</h2>
            <p>
              The Ganesh Puja 2026 Finance Portal is a community-managed financial ledger platform designed exclusively to maintain transparency for festival collections, out-of-pocket expenses, cash handovers, and treasury balance verification for Ganesh Puja 2026.
            </p>
          </section>

          <section className="space-y-1">
            <h2 className="text-sm font-bold text-amber-400">2. Financial Disclaimer</h2>
            <p>
              This application is a non-commercial community tool. Digital receipts generated by the application serve as digital confirmation records for community chanda collections and treasury settlement tracking. All financial transactions are subject to internal audit by the appointed Treasurers and Super Admins.
            </p>
          </section>

          <section className="space-y-1">
            <h2 className="text-sm font-bold text-amber-400">3. User Conduct & Role Verification</h2>
            <p>
              Users must log in using a valid Google Account. Access to administrative controls (recording collections, approving handovers, reimbursing expenses) is restricted by serverless Role-Based Access Control (RBAC). Unauthorized attempts to manipulate accounting ledgers are prohibited.
            </p>
          </section>

          <section className="space-y-1">
            <h2 className="text-sm font-bold text-amber-400">4. Limitation of Liability</h2>
            <p>
              The platform administrators and developers provide this software "as is" without warranty of any kind. While every effort is made to maintain database accuracy, official financial records are governed by the committee's final audit report.
            </p>
          </section>

          <section className="space-y-1">
            <h2 className="text-sm font-bold text-amber-400">5. Contact Information</h2>
            <p>
              For legal inquiries, feedback, or administrative support, contact:
              <br />
              <span className="font-mono text-amber-400">luhurenbaiclub@gmail.com</span>
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}
